variables:
  DOCKER_REG: "dockerepo.coe001.net"
  VER: "v1.0.${CI_PIPELINE_IID}"

stages:
  - build

package_build:
  only:
    - master
  except:
    - tags
  stage: build
  tags:
    - docker-build
  script:
    - docker build -t facade/app:${VER} ./
    - docker tag facade/app:${VER} ${DOCKER_REG}/facade/app:${VER}
    - docker push ${DOCKER_REG}/facade/app:${VER}
    - echo "Congratulation, we are here finanlly. ${VER}"
