variables:
  DOCKER_REG: "{DOCKER_REPO}"
  VER: "v1.0.${CI_PIPELINE_IID}"

stages:
  - build

package_build:
  only:
    - master
  except:
    - tags
  stage: build
  tags:
    - docker-build
  script:
    - docker build -t {$PRO_NAME}/{$APP_NAME}:${VER} ./
    - docker tag {$PRO_NAME}/{$APP_NAME}:${VER} ${DOCKER_REG}/{$PRO_NAME}/{$APP_NAME}:${VER}
    - docker push ${DOCKER_REG}/{$PRO_NAME}/{$APP_NAME}:${VER}
    - echo "Congratulation, we are here finanlly. ${VER}"
